error[E0499]: cannot borrow `app_update_manager` as mutable more than once at a time    --> src/main.rs:57:15     | 57  |         match app_update_manager.get_status() {     |               ^^^^^^^^^^^^^^^^^^ second mutable borrow occurs here ... 122 |                                                 let async_spawn = spawn(app_update_manager.update_apps());     |                                                                   ---------------------------------------     |                                                                   |     |     |                                                                   |     first mutable borrow occurs here     |                                                                   argument requires that `app_update_manager` is borrowed for `'static`